[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false

[build.environment]
  NODE_VERSION = "20"
  NPX_YES = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_SITE_URL = "https://hotelsamb.com"
  NEXT_PUBLIC_SUPABASE_URL = "https://gnrnkhcavvgfdqysggaa.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imducm5raGNhdnZnZmRxeXNnZ2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MDQ5NzMsImV4cCI6MjA3MDk4MDk3M30.kgHxvVA1JPsaoZzTqkIlPHbo73EYSrAcnhdIQjyh5JI"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imducm5raGNhdnZnZmRxeXNnZ2FhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTQwNDk3MywiZXhwIjoyMDcwOTgwOTczfQ.U5JcexFxjN-9OtYjIfgvUG_SiocvudtXJu_EZKCcweM"

# Static file headers - force deployment refresh
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"